name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Start the app
        run: npm run start
        env:
          CI: true

      #   - name: Wait for app to start
      #     uses: jakejarvis/wait-action@master
      #     with:
      #       wait-on: https://cypress-course-apps-signup.vercel.app
      #       timeout: 60
      #       time: 10

      - name: Run Cypress tests
        run: npm run test:e2e
